//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX23A.RC
//
#define IDR_MAINFRAME                   2
#define IDB_QUEEN                       25
#define IDD_ABOUTBOX                    100
#define IDC_BITS1                       101
#define IDB_PARTY                       102
#define IDC_BITS4                       102
#define IDD_BITS                        103
#define IDC_BITS8                       103
#define IDC_BITS24                      104
#define IDB_HORSE                       105
#define IDC_COMPRESSION                 105
#define ID_EDIT_PASTE_FROM              32768
#define ID_EDIT_COPY_TO                 32769
#define ID_VIEW_SHRINK                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
