//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX11A.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDC_EDIT_COPY                   102
#define IDC_EDIT_CUT                    103
#define IDC_EDIT_PASTE                  104
#define IDC_MESSAGE                     106
#define IDD_BITMAP                      108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
