//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX26B.RC
//
#define IDR_MAINFRAME                   2
#define IDS_TOO_MANY_ROWS               3
#define IDD_ABOUTBOX                    100
#define IDC_EDIT1                       101
#define IDD_STUDENT                     101
#define IDC_EDIT2                       102
#define IDB_INSERT                      103
#define IDB_CANCEL                      104
#define IDB_UPDATE                      105
#define IDB_CLEAR                       106
#define IDB_DELETE                      107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
