//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX13B.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define ID_MY_STATUS_BAR                101
#define ID_INDICATOR_SHIFT              57620
#define ID_INDICATOR_CTRL               57621
#define ID_INDICATOR_ALT                57622

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
