//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX22B.RC
//
#define IDR_MAINFRAME                   2
#define IDD_EX22BDLG                    101
#define ID_COMPUTE                      1000
#define IDC_COMPUTE                     1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_RADIO1                      1003
#define IDC_RADIO2                      1004
#define IDC_RADIO3                      1005
#define IDC_RADIO4                      1006
#define IDC_EDIT3                       1007
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
