//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX16A.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_STUDENT                     101
#define ID_POS_HOME                     101
#define ID_POS_END                      102
#define ID_POS_PREV                     103
#define ID_POS_NEXT                     104
#define ID_POS_DEL                      105
#define ID_POS_INS                      106
#define IDC_CLEAR                       110
#define IDC_NAME                        1000
#define IDC_GRADE                       1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
