//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX06A.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDC_TEXT1                       1000
#define IDC_TEXT2                       1001
#define IDC_GROUPBOX1                   1002
#define IDC_GROUPBOX2                   1003
#define IDC_SKILL                       1004
#define IDC_TEXT3                       1006
#define IDC_EDUC                        1008
#define IDC_LANG                        1009
#define IDC_TEXT5                       1010
#define IDC_NAME                        1020
#define IDC_SSN                         1024
#define IDC_BIO                         1028
#define IDC_CAT                         1030
#define IDC_RADIO2                      1034
#define IDC_LIFE                        1040
#define IDC_DIS                         1044
#define IDC_MED                         1048
#define IDC_SPECIAL                     1050
#define IDC_OK                          1054
#define IDC_DEPT                        1060
#define IDC_LOYAL                       1070
#define IDC_RELY                        1074
#define IDR_DIALOG1                     28674
#define IDD_DIALOG1                     28674

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
