// Machine generated IDispatch driver class(es) created with ClassWizard.

/////////////////////////////////////////////////////////////////////////////
// _DHello wrapper class

class _DHello : public COleDispatchDriver
{
// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid type information
	// method 'AddRef' not emitted because of invalid type information
	// method 'Release' not emitted because of invalid type information
	void SetHelloMessage(const char* p0);
	CString GetHelloMessage();
	CString SayHello();
};

