//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX25E.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ALARMDIALOG                 102
#define IDC_HRS                         1000
#define IDC_MINS                        1005
#define IDC_SECS                        1006
#define ID_EXCELOLE_LOAD                32772
#define ID_EXCELOLE_EXECUTE             32773
#define ID_CLOCKOLE_LOAD                32774
#define ID_CLOCKOLE_REFRESHTIME         32775
#define ID_CLOCKOLE_UNLOAD              32776
#define ID_DLLOLE_LOAD                  32777
#define ID_DLLOLE_GETDATA               32778
#define ID_DLLOLE_UNLOAD                32779
#define ID_CLOCKOLE_CREATEALARM         32781
#define ID_MARKETOLE_LOAD               32782
#define ID_MARKETOLE_GETAVERAGE         32783
#define ID_MARKETOLE_UNLOAD             32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
