//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX15A.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_EX15A_FORM                  101
#define IDC_NAME                        1000
#define IDC_GRADE                       1001
#define IDC_ENTER                       1002
#define ID_EDIT_CLEARALL                32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
