//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX15B.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_STUDENT                     101
#define IDC_CLEAR                       110
#define IDC_NAME                        1000
#define IDC_GRADE                       1001
#define ID_POS_HOME                     0x8001
#define ID_POS_END                      0x8002
#define ID_POS_PREV                     0x8003
#define ID_POS_NEXT                     0x8004
#define ID_POS_DEL                      0x8005
#define ID_POS_INS                      0x8006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         104
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
