//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX08A.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG1                     101
#define IDC_GRID1                       101
#define IDC_ADDROW                      102
#define IDC_DELETEROW                   103
#define IDC_UPDATEVALUE                 104
#define IDC_VALUE                       105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
