//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX20B.RC
//
#define IDR_MAINFRAME                   2
#define IDR_POEMTYPE                    3
#define IDD_ABOUTBOX                    100
#define IDR_STRINGVIEW                  101
#define IDR_HEXVIEW                     102
#define ID_WINDOW_NEW1                  32768
#define ID_WINDOW_NEW2                  32769

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
