//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MATPLAN.RC
//
#define IDR_MAINFRAME                   2
#define IDR_MATTYPE                     3
#define IDD_ABOUTBOX                    100
#define IDR_LISTVIEW                    101
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_CONTROL_VALUE         101
#define IDR_PLANVIEW                    102
#define IDR_LISTBOX                     103
#define IDP_EXIT_DLG                    104
#define _APS_NEXT_SYMED_VALUE           105
#define IDC_DESC                        103
#define IDC_LENGTH                      107
#define IDC_WIDTH                       108
#define IDC_SHEET                       110
#define IDC_X                           111
#define IDC_Y                           112
#define IDC_CANCEL                      114
#define IDC_INSERT                      116
#define IDC_DELETE                      117
#define IDC_CLEAR                       118
#define IDC_UPDATE                      119
#define IDD_FORM                        120
#define ID_WINDOW_NEW1                  59395
#define ID_WINDOW_NEW2                  59396
#define _APS_NEXT_COMMAND_VALUE         59397
