//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX24B.RC
//
#define IDR_MAINFRAME                   2
#define IDR_EX24BTYPE                   3
#define IDS_TOO_MANY_ROWS               4
#define MAXCOLS                         100
#define IDD_ABOUTBOX                    100
#define IDD_QUERY_BAR                   101
#define ID_QUERY_TABLES                 103
#define IDD_TABLE_SELECT                103
#define IDC_SORT                        104
#define IDC_FILTER                      105
#define ID_QUERY_SORT                   106
#define IDC_LIST1                       107
#define MAXROWS                         2500
#define ID_FILE_CONNECT                 32768
#define ID_FILE_DISCONNECT              32769
#define ID_QUERY_REQUERY                32771
#define IDC_REQUERY                     32771
#define ID_QUERY_FILTER                 32772
#define ID_QUERY_BAR                    0xe810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         108
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
