//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX22C.RC
//
#define	WM_START	WM_USER + 5

#define IDR_MAINFRAME                   2
#define ID_WINDOW_CLOSE_ALL             40002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
