//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EX25C.RC
//
#define IDD_PROMPT                      101
#define IDC_ENABLEALL                   512
#define IDC_TEXT_DATA                   1000
#define IDC_LONG_DATA                   1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
